version: 2
jobs:
  build:
    working_directory: ~/hraftd/src/github.com/otoolep/hraftd
    docker:
      - image: cimg/go:1.21.0
    resource_class: large

    steps:
        - checkout
        - run: go vet .
        - run: go get -t -d -v ./...
        - run: go test -timeout 60s -v ./...
        - run:
            command: go test -race -timeout 120s -v ./...
            environment:
                GORACE: "halt_on_error=1"

